### ISSUE TITLE
Unable to install the plugin on version MM 7.1.2

### ISSUE THREAD

**Issue by msounkere** [ONLYOFFICE/onlyoffice-mattermost#15]
After many check, this plugin is not compatible with Mattermost v7. do you have an upgrade please.

**Comment by VincentSC** [comment]
Still getting this:
> This plugin failed to start. unable to start plugin: com.onlyoffice.mattermost: Unrecognized remote plugin message: This usually means that the plugin is either invalid or simply needs to be recompiled to support the latest protocol.

**Comment by msounkere** [comment]
@VincentSC , it works very well for us with mm latest version 7.3.0. You may have to delete the existing installation and re-upload the plug-in.
