### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by ydelattre** [ONLYOFFICE/onlyoffice-mattermost#27]
Hello,

I'm trying to use the ONLYOFFICE plugin from Mattermost.
However, I'm getting an error "500 internal server error" :

![image](https://user-images.githubusercontent.com/11867613/211046722-aa503b64-928c-4e43-9c0f-2c1650e21c44.png)

From the console log : 

```
warn [2023-01-06 16:19:14.465 +01:00] Health check failed for plugin caller="plugin/health_check.go:59" id=com.onlyoffice.mattermost error="plugin RPC connection is not responding"
warn [2023-01-06 16:19:14.465 +01:00] error closing client during Kill caller="plugin/hclog_adapter.go:70" plugin_id=com.onlyoffice.mattermost wrapped_extras="errconnection is shut down"
warn [2023-01-06 16:19:14.465 +01:00] plugin failed to exit gracefully caller="plugin/hclog_adapter.go:72" plugin_id=com.onlyoffice.mattermost
error [2023-01-06 16:19:34.197 +01:00] RPC call to OnActivate plugin failed. caller="plugin/client_rpc.go:268" plugin_id=com.onlyoffice.mattermost error="unexpected EOF"
error [2023-01-06 16:19:34.197 +01:00] plugin process exited caller="plugin/hclog_adapter.go:79" plugin_id=com.onlyoffice.mattermost wrapped_extras="pathplugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64pid1633errorexit status 2"
error [2023-01-06 16:19:34.217 +01:00] RPC call OnConfigurationChange to plugin failed. caller="plugin/client_rpc_generated.go:67" plugin_id=com.onlyoffice.mattermost error="connection is shut down"
```

Versions :
- Mattermost : 7.5.2
- Plugin : 1.1.0
- OnlyOffice Docs : 7.2.1

Is the plugin really compatible with version 7.5.2 of Mattermost ?

Thanks for your help.
Regards.
Yoann.

**Comment by ATATSOLVE2020** [comment]
I too get the same error message.

**Comment by Nsenz** [comment]
@ydelattre, Hello!

Thanks for your feedback. We will look into the problem as soon as possible!

**Comment by abbasharoon** [comment]
Same here:
```
{"timestamp":"2023-01-14 15:54:45.778 Z","level":"warn","msg":"Health check failed for plugin","caller":"plugin/health_check.go:59","id":"com.onlyoffice.mattermost","error":"plugin RPC connection is not responding"}
{"timestamp":"2023-01-14 15:54:45.778 Z","level":"warn","msg":"error closing client during Kill","caller":"plugin/hclog_adapter.go:70","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"errconnection is shut down"}
{"timestamp":"2023-01-14 15:54:45.778 Z","level":"warn","msg":"plugin failed to exit gracefully","caller":"plugin/hclog_adapter.go:72","plugin_id":"com.onlyoffice.mattermost"}
{"timestamp":"2023-01-14 15:54:45.954 Z","level":"error","msg":"RPC call to OnActivate plugin failed.","caller":"plugin/client_rpc.go:268","plugin_id":"com.onlyoffice.mattermost","error":"unexpected EOF"}
{"timestamp":"2023-01-14 15:54:45.955 Z","level":"error","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:79","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"pathplugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64pid21025errorexit status 2"}
{"timestamp":"2023-01-14 15:55:00.833 Z","level":"error","msg":"Plugin failed to ServeHTTP, RPC call failed","caller":"plugin/client_rpc.go:423","plugin_id":"com.onlyoffice.mattermost","error":"connection is shut down"}
{"timestamp":"2023-01-14 15:55:05.835 Z","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","caller":"plugin/client_rpc.go:397","plugin_id":"com.onlyoffice.mattermost","error":"timeout waiting for accept"}
{"timestamp":"2023-01-14 15:55:05.835 Z","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","caller":"plugin/client_rpc.go:378","plugin_id":"com.onlyoffice.mattermost","serve_http_stream_id":3,"error":"timeout waiting for accept"}
```

**Comment by Nsenz** [comment]
@abbasharoon, @ydelattre could you please share more details about the deployment? The plugin seems to be working fine with MM 7.5.2. There is a visual problem with the spinner though.

**Comment by Nsenz** [comment]
@abbasharoon, @ydelattre Indeed there is a timeout problem OnActivate and OnConfigurationChange. Will have a look at that! Thanks for your feedback!

**Comment by abbasharoon** [comment]
@Nsenz here is my setup:

Ubuntu 18.04
MM: 7.5.2
OO-MM Plugin: 1.1.0

MM is installed via their docker setup: https://mattermost.com/deploy/
OO Document server is also a docker instance https://github.com/ONLYOFFICE/Docker-DocumentServer

Both are behind Nginx reverse proxy.

**Comment by igwyd** [comment]
Hello @abbasharoon, i tested the same deploy as you and no errors, i think it's a reverse proxy issue, not plugin.

**Comment by ydelattre** [comment]
@Nsenz :
MM is installed via Docker and OO Docs on K8S.
HAProxy is used in front of OO Docs and then NGINX Ingress controller is used on K8S, so could it be a reverse proxy issue but no idea what may be causing it.... 🧐

**Comment by Nsenz** [comment]
@ydelattre will ask our DevOps to have a look at that!

**Comment by ydelattre** [comment]
@Nsenz Great ! Thanks :)

**Comment by ydelattre** [comment]
Hello @igwyd @Nsenz 
I looked again.
When i activate the plugin, it successfully check the version :
HTTP request from MM plugin : 
```
{"exp":1674484628,"iat":1674484568,"c":"version","token":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}
```
HTTP answer from OO Docs :
```
{"error":0,"version":"7.2.2.56"}
```
And quickly after the plugin crashed with this error :

```
{"timestamp":"2023-01-23 15:35:38.676 +01:00","level":"debug","msg":"panic: runtime error: invalid memory address or nil pointer dereference","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.onlyoffice.mattermost"}
{"timestamp":"2023-01-23 15:35:38.677 +01:00","level":"debug","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x965d0b]","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.onlyoffice.mattermost"}
```
Don't know how this error could be related to a reverse proxy issue :-/
FYI, the plugin was downloaded from this repo in the release page.

Thanks for your help !

**Comment by ydelattre** [comment]
So far all test was done in our test env. I tested the plugin in our dev env : it practically works (little problem with mixed contents) but the plugin start successfully.
The difference between dev and test env : file storage is done on S3 in our test env
Furthermore, the stack trace mentioned :
```
{"timestamp":"2023-01-23 15:36:08.723 +01:00","level":"debug","msg":"github.com/mattermost/mattermost-server/v6/model.(*FileSettings).ToFileBackendSettings(0x7f030090b6e0, 0x10)","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.onlyoffice.mattermost"}
```
It's a lead, i think :)

**Comment by Nsenz** [comment]
Hello @ydelattre!

Do you know if the crash happens after your editing session? Please shed some light on the steps you take in order for us to recreate the exact issue. Also, it would be helpful if you could share logs from your dev environment. @Eloncase, could you please have a look at that?

**Comment by Nsenz** [comment]
@ydelattre, I suppose our calls to MM's filestore might cause the problem provided the bug occurs during/after editing.

**Comment by ydelattre** [comment]
Hello @Nsenz,
the crash happen before the editing session just after enabling the plugin.
And then this message is shown in the plugin management page : 
`This plugin crashed multiple times and is no longer running. Check your system logs for errors.`

In our dev env, the plugin start without problem :
```
{"timestamp":"2023-01-24 14:51:38.207 +01:00","level":"debug","msg":"starting plugin","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"pathplugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64args[plugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64]"}
{"timestamp":"2023-01-24 14:51:38.208 +01:00","level":"debug","msg":"plugin started","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"pathplugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64pid780"}
{"timestamp":"2023-01-24 14:51:38.208 +01:00","level":"debug","msg":"waiting for RPC address","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"pathplugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64"}
{"timestamp":"2023-01-24 14:51:38.444 +01:00","level":"debug","msg":"using plugin","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"version1"}
{"timestamp":"2023-01-24 14:51:38.464 +01:00","level":"debug","msg":"plugin address","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"networkunixaddress/tmp/plugin577205606timestamp2023-01-24T14:51:38.433+0100"}
{"timestamp":"2023-01-24 14:51:38.594 +01:00","level":"info","msg":"[ONLYOFFICE CMD]: The server responded without errors","caller":"app/plugin_api.go:973","plugin_id":"com.onlyoffice.mattermost"}
{"timestamp":"2023-01-24 14:51:38.956 +01:00","level":"info","msg":"[ONLYOFFICE CMD]: The server responded without errors","caller":"app/plugin_api.go:973","plugin_id":"com.onlyoffice.mattermost"}
```

Hmmmmm, maybe i found something :

https://github.com/ONLYOFFICE/onlyoffice-mattermost/blob/b129dc18bff0a5446a406d12a142f6bdd876200c/server/cmd/plugin.go#L107

There is only one argument in this method : `ToFileBackendSettings(license != nil && *license.Features.Compliance)`
But in Mattermost code, this method need 2 arguments :
```go
func (s *FileSettings) ToFileBackendSettings(enableComplianceFeature bool, skipVerify bool) filestore.FileBackendSettings {
```
(https://github.com/mattermost/mattermost-server/blob/1fdedf30f10628fa20f5d9d7b72993c3d187bfaf/model/config.go#L1562)

If you look at the method, second argument `skipVerify` is only use if local storage is not enable. Could explain why the plugin crash in our dev env (local storage) and not in our test env (S3 storage).

**Comment by Nsenz** [comment]
Hello @ydelattre! Apparently, S3 does cause the problem. We'll look into the problem! Thanks again for your feedback

**Comment by LinneyS** [comment]
Released
https://github.com/ONLYOFFICE/onlyoffice-mattermost/releases/tag/v1.1.1
