### ISSUE TITLE
How to display the full file name？

### ISSUE THREAD

**Issue by cedarice** [ONLYOFFICE/onlyoffice-mattermost#43]
Sometimes user upload multiple files with similar file names, but mattermost cannot display the full file names.  This results in the user not being able to distinguish files well. How to display the full file name？

**Comment by Nsenz** [comment]
@cedarice hi there! I believe that you are talking about the mattermost feature, not our plugin. Could you please elaborate on you idea (where exactly you want to display the full names)?

**Comment by cedarice** [comment]
Sorry!
