### ISSUE TITLE
Unable to enable the ONLYOFFICE plugin

### ISSUE THREAD

**Issue by ynott** [ONLYOFFICE/onlyoffice-mattermost#7]
condition: 
I'm trying to use the ONLYOFFICE plugin from mattermost.
However, I'm getting an error and I'm not able to activate the ONLYOFFICE plugin properly.

versions:
- Mattermost: 5.39.0
- ONLYOFFICE Plugin:1.0.0
- ONLYOFFICE 6.3.1

Expected behavior:
The ONLYOFFICE plugin should be activated

Actual behavior:
When I press the enable button, it immediately returns to disabled.

Settings:
Document Editing Service address: https://<FQDN of the actual server>/
Secret key (leave blank to disable): 

![image](https://user-images.githubusercontent.com/2724312/136494112-3a907fcd-bcfe-4165-8630-64773ca2be0e.png)

Logs:

<details>
<summary> grep mattermost.log on mattermost server </summary>

```
$ grep "onlyoffice" mattermost.log

{"level":"debug","ts":1633662790.9968615,"caller":"plugin/hclog_adapter.go:52","msg":"starting plugin","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"path/opt/mattermost-data/plugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64args[/opt/mattermost-data/plugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64]"}
{"level":"debug","ts":1633662790.9973962,"caller":"plugin/hclog_adapter.go:52","msg":"plugin started","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"path/opt/mattermost-data/plugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64pid19881"}
{"level":"debug","ts":1633662790.997437,"caller":"plugin/hclog_adapter.go:52","msg":"waiting for RPC address","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"path/opt/mattermost-data/plugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64"}
{"level":"debug","ts":1633662791.0458398,"caller":"plugin/hclog_adapter.go:52","msg":"plugin address","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"address/tmp/plugin1056552694networkunixtimestamp2021-10-08T12:13:11.045+0900"}
{"level":"debug","ts":1633662791.045999,"caller":"plugin/hclog_adapter.go:52","msg":"using plugin","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"version1"}
{"level":"error","ts":1633662791.1856277,"caller":"go-plugin@v1.4.2/stream.go:15","msg":" call to OnConfigurationChange failed, error: [ONLYOFFICE]: The server responded with an error: 6","plugin_id":"com.onlyoffice.mattermost","source":"plugin_stderr"}
{"level":"debug","ts":1633662791.2379296,"caller":"plugin/hclog_adapter.go:52","msg":"plugin process exited","plugin_id":"com.onlyoffice.mattermost","wrapped_extras":"path/opt/mattermost-data/plugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64pid19881"}
{"level":"debug","ts":1633662791.238019,"caller":"plugin/hclog_adapter.go:54","msg":"plugin exited","plugin_id":"com.onlyoffice.mattermost"}

```

</details>

**Comment by ynott** [comment]
Thanks @Nsenz,

Hummn, The JWT Secret you are referring to is the JWT_SECRET from the following site, right?

[JWT options](https://helpcenter.onlyoffice.com/installation/docs-enterprise-install-ubuntu.aspx)

I'm using the same ONLYOFFICE Docs EE on Nextcloud.
But it is working with the same JWT_SECRET and there is no problem.
I confirmed that it works with the same Secret Key.

The Secret string has `$` and `#` in it. Is it possible that this is affecting the Token Validation Error?

**Comment by Nsenz** [comment]
@ynott Works fine with the aforementioned symbols.

**Comment by ynott** [comment]
This Issue will be closed.
If there are any problems, it will be reopened.
